const os = require('os')
console.log('os = ',os.platform())
// const osKeys = Object.keys(os)
console.log('totalMemory = ',os.totalmem())
console.log('cups = ',os.cpus())
console.log('hostname = ',os.hostname())